apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
replicas:
- count: 1
  name: deployment
images:
- name: 119834080691.dkr.ecr.ap-northeast-1.amazonaws.com/black
  newTag: 00d2edeb09be85f45ef419d3f871f6c0008cd21a
