apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

images:
- name: 119834080691.dkr.ecr.ap-northeast-1.amazonaws.com/black
  newTag: e3fea37b5e63af3815754b4cf196662ab69a8271
