apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
images:
- name: 119834080691.dkr.ecr.ap-northeast-1.amazonaws.com/black
  newTag: 05af373f9677b1b89e3e08645f449bb211d66478
