apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namePrefix: prod-
images:
- name: 119834080691.dkr.ecr.ap-northeast-1.amazonaws.com/black
  newTag: 00cdeb32676540e4b83e0f3c47375a475aa446a8
